<?php

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * For user_profile_form.
 */
function clear_password_field_form_user_profile_form_alter(&$form, &$form_state) {
  backdrop_add_js(backdrop_get_path('module', 'clear_password_field') . '/clear_password_field_edit.js');
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * For user_register.
 */
function clear_password_field_form_user_register_form_alter(&$form, &$form_state) {
  $form['account']['name']['#attributes'] = array('autocomplete' => array('off'));
  $form['account']['mail']['#attributes'] = array('autocomplete' => array('off'));
  backdrop_add_js(backdrop_get_path('module', 'clear_password_field') . '/clear_password_field_register.js');
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * For user_login.
 */
function clear_password_field_form_user_login_alter(&$form, &$form_state) {
  $form['pass']['#attributes'] = array('autocomplete' => array('off'));
  backdrop_add_js(backdrop_get_path('module', 'clear_password_field') . '/clear_password_field_login.js');
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * For user_login_block.
 */
function clear_password_field_form_user_login_block_alter(&$form, &$form_state) {
  $form['pass']['#attributes'] = array('autocomplete' => array('off'));
  backdrop_add_js(backdrop_get_path('module', 'clear_password_field') . '/clear_password_field_login.js');
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 *
 * For password_policy_password_tab from the Password Policy module.
 */
function clear_password_field_form_password_policy_password_tab_alter(&$form, &$form_state) {
  backdrop_add_js(backdrop_get_path('module', 'clear_password_field') . '/clear_password_field_edit.js');
}
