<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function clear_password_field_form_user_admin_settings_alter(&$form, &$form_state) {
  $form['clear_password_field'] = array(
    '#type' => 'fieldset',
    '#title' => t('Clear password field'),
  );
  $form['clear_password_field']['clear_password_field'] = array(
    '#type' => 'radios',
    '#title' => t('Enable'),
    '#options' => array(
      0 => t('Disabled'),
      1 => t('Enabled'),
    ),
    '#default_value' => variable_get('clear_password_field', 1),
    '#description' => t('Enable this setting to clear the saved password from the password field whenever a user account is edited, a new user is going to be added, or a user is trying to register. <strong>Note: this will not clear the saved password from the web browser, it will just clear the field to improve usability.</strong>'),
  );
}

/**
 * Implementation of hook_form_FORM_ID_alter() for user_profile_form.
 */
function clear_password_field_form_user_profile_form_alter(&$form, &$form_state) {
  if (variable_get('clear_password_field', 1) == 1) {
    drupal_add_js(drupal_get_path('module', 'clear_password_field') . '/clear_password_field_edit.js');
  }
}

/**
 * Implementation of hook_form_FORM_ID_alter() for user_register.
 */
function clear_password_field_form_user_register_alter(&$form, &$form_state) {
  if (variable_get('clear_password_field', 1) == 1) {
    drupal_add_js(drupal_get_path('module', 'clear_password_field') . '/clear_password_field_register.js');
  }
}
